name: Aptos Move Test for Compiler V2
description: Runs Aptos Move tests with compiler V2
inputs:
  GIT_CREDENTIALS:
    description: "Optional credentials to pass to git. Useful if you need to pull private repos for dependencies"
    required: false

runs:
  using: composite
  steps:
    # Checkout the repository and setup the rust toolchain
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0 # Fetch all git history for accurate target determination

    # Output the changed files
    - name: Output the changed files
      run: cargo x changed-files -vv
      shell: bash

    # Output the affected packages
    - name: Output the affected packages
      run: cargo x affected-packages -vv
      shell: bash

    # Run Aptos Move tests with compiler V2
    - name: Run Aptos Move tests with compiler V2
      run: cargo x targeted-compiler-v2-tests -vv --release --profile ci --locked --no-fail-fast
      shell: bash
      env:
        MOVE_COMPILER_V2: true
        RUST_MIN_STACK: 4297152
        MVP_TEST_ON_CI: true
        SOLC_EXE: /home/runner/bin/solc
        Z3_EXE: /home/runner/bin/z3
        CVC5_EXE: /home/runner/bin/cvc5
        DOTNET_ROOT: /home/runner/.dotnet
        BOOGIE_EXE: /home/runner/.dotnet/tools/boogie

    # Run move_pr.sh -i2
    - name: Run move_pr.sh with V2 flag
      shell: bash
      run: third_party/move/scripts/move_pr.sh -i2
      env:
        RUST_MIN_STACK: 4297152
        MVP_TEST_ON_CI: true
        SOLC_EXE: /home/runner/bin/solc
        Z3_EXE: /home/runner/bin/z3
        CVC5_EXE: /home/runner/bin/cvc5
        DOTNET_ROOT: /home/runner/.dotnet
        BOOGIE_EXE: /home/runner/.dotnet/tools/boogie
